### ISSUE TITLE
Portal color correction failure

### ISSUE THREAD

**Issue by MaddTheSane** [nillerusr/source-engine#215] opened 2023-03-15 00:31 UTC
When color correction is enabled on Ventura, Portal 1 displays… strangely:

With color correction:
![Screenshot 2023-03-14 at 6 18 56 PM](https://user-images.githubusercontent.com/719492/225171550-a12734a6-0bee-4e74-a6b9-a9562e298a43.png)
Without color correction:
![Screenshot 2023-03-14 at 6 23 33 PM](https://user-images.githubusercontent.com/719492/225171660-6ecc9ff3-f32d-433e-9437-e69529febbdd.png)

Specs:
AMD Radeon Pro 580
Intel Core i7-7700K @ 4.20 GHz
macOS 13.2.1

**Comment by SanyaSho** [comment] 2023-03-17 05:17
duplicate of #137

**Closed** 2023-03-22 08:17 UTC
